base/urls.py
from django.urls import path,include
from . import views
app_name = 'base'


urlpatterns = [
    path('',views.HomeView.as_view(), name='home')
]

course/urls.py
from django.urls import path,include
from .views import *
app_name = 'courses'


urlpatterns = [
    path('all/', CourseListView.as_view(),name='all'),
    path('add-course/', AddCourseView.as_view(),name='add-course'),
    path('course/<int:pk>', CourseView.as_view(),name='course'),
]

smartEd/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls'),name='base'),
    path('accounts/', include('accounts.urls'), name='accounts'),
    path('courses/', include('course.urls'), name='course'),
    path('rewards/', include('reward.urls'), name='reward'),
]

course/models.py
from django.db import models
from accounts.models import Teacher,Student
from django.core.validators import FileExtensionValidator


video_extensions = ['.mp4', '.mov', '.avi', '.wmv', '.mkv', '.flv']
photo_extensions = ['.jpg', '.jpeg', '.png', '.gif', '.bmp', '.svg']
pdf_extensions = ['.pdf']
document_extensions = ['.doc', '.docx', '.txt', '.rtf', '.odt', '.wps']
presentation_extensions = ['.ppt', '.pptx', '.odp', '.key']
csv_extensions = ['.csv']
text_extensions = ['.txt']

EXTENSIONS = ['.mp4', '.mov', '.avi', '.wmv', '.mkv', '.flv','.jpg','.pdf', '.jpeg', '.png', '.gif', '.bmp', '.svg','.doc', '.docx', '.txt', '.rtf', '.odt', '.wps','.ppt', '.pptx', '.odp', '.key','.cvs','.txt']


class Course(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    owner = models.ForeignKey(Teacher, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class Lesson(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    content = models.FileField(blank=True,upload_to = 'content/',validators=[FileExtensionValidator(allowed_extensions=EXTENSIONS)])
    course = models.ForeignKey(Course, on_delete=models.CASCADE)

    def __str__(self):
        return self.name
    

class Assignment(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    course = models.ForeignKey(Course, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class Quiz(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE)

    def __str__(self):
        return self.name
    
class Question(models.Model):
    text = models.TextField()
    answer = models.TextField()
    points = models.IntegerField()
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)

    def __str__(self):
        return self.text
    
class Enrollment(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.student.user.username} enrolled in {self.course.name}"

course/views.py
from django.shortcuts import render, redirect
from django.views.generic import View,ListView,DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from accounts.models import Student,Teacher
from .models import *
from django.http import Http404


class CourseListView(LoginRequiredMixin, ListView):
    template_name = 'courses.html'
    context_object_name = 'courses'

    def get_queryset(self):
        user = self.request.user
        if Student.objects.filter(user=user).exists():
            queryset = Enrollment.objects.filter(student__user=user).select_related('course')
            print(queryset)
            return [enrollment.course for enrollment in queryset]
        elif Teacher.objects.filter(user=user).exists():
            teacher = Teacher.objects.get(user=user)
            queryset = Course.objects.filter(owner=teacher).order_by('name')
            print(queryset)
            return queryset
        else:   
            return Course.objects.none()
        
class AddCourseView(LoginRequiredMixin,View):

    def get(self,request):
        if not Teacher.objects.filter(user = self.request.user):
            print("==========not a teacher=============")
            raise Http404("Not Authorised")
        return render(request,'add_course.html')

    def post(self, request):
        # Get course details from form data
        print(request.POST)
        course_name = request.POST.get('name')
        course_description = request.POST.get('description')

        # Create new course object
        course = Course(name=course_name, description=course_description,owner = self.request.user.teacher)
        course.save()

        # Get lesson details from form data
        lesson_count = int(request.POST.get('lesson-count'))
        for i in range(1, lesson_count):
            lesson_name = request.POST.get(f'lesson-name-{i}')
            lesson_description = request.POST.get(f'lesson-description-{i}')
            lesson_content = request.POST.get(f'lesson-file-{i}')
            print(lesson_content)
            # Create new lesson object and add it to course
            lesson = Lesson(name=lesson_name, description=lesson_description, course=course,content = lesson_content)
            print(lesson.content)
            lesson.save()

        return redirect('courses:all')
    
class CourseView(LoginRequiredMixin,DetailView):
    model = Course
    template_name = 'course_detail.html'
    

course/templates/add_course.html
<!DOCTYPE html>
<html>
  <head>
    <title>Add Course and Lessons</title>
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    />
    <style>
      body {
        font-family: Arial, sans-serif;
      }
      h1 {
        margin-top: 0;
      }
      form {
        /* max-width: 600px; */
        margin: 0 auto;
      }
      label {
        display: block;
        margin-bottom: 5px;
        font-weight: bold;
      }
      input[type='text'],
      textarea,
      input[type='file'] {
        width: 100%;
        padding: 10px;
        margin-bottom: 20px;
        border-radius: 5px;
        border: 1px solid #ccc;
      }
      input[type='submit'],
      button {
        background-color: #4caf50;
        color: #fff;
        border: none;
        padding: 10px 20px;
        border-radius: 5px;
        cursor: pointer;
      }
      button:hover {
        background-color: #3e8e41;
      }
      .lesson-fields {
        border: 1px solid #ccc;
        padding: 20px;
        margin-bottom: 20px;
        position: relative;
      }
      .remove-lesson-btn {
        position: absolute;
        right: 15px;
        top: 10px;
        background-color: #f44336;
        padding: 5px 10px;
        color: #fff;
        border: none;
        border-radius: 5px;
        cursor: pointer;
      }
      .remove-lesson-btn:hover {
        background-color: #da190b;
      }
    </style>
  </head>
  <body>
    <div
      style="background-color: rgb(244, 244, 244)"
      class="container mt-4 p-4 border"
    >
      <h1 style="text-align: center">Add Course Details</h1>
      {% if messages %}
      <ul>
        {% for message in messages %}
        <li>{{ message }}</li>
        {% endfor %}
      </ul>
      {% endif %}
      <form id="my-form" method="post" action="{% url 'courses:add-course' %}">
        {% csrf_token %}
        <label for="name">Course Name:</label>
        <input type="text" name="name" id="name" required /><br /><br />
        <label for="description">Course Description:</label>
        <textarea name="description" id="description" required></textarea
        ><br /><br />
        <h1>Add Lessons</h1>
        <div id="lesson-fields-container">
          <div class="lesson-fields" id="lesson-1">
            <label for="lesson-name-1">Lesson 1 Name:</label>
            <input
              type="text"
              id="lesson-name-1"
              name="lesson-name-1"
              required
            />
            <label for="lesson-description-1">Lesson 1 Description:</label>
            <textarea
              id="lesson-description-1"
              name="lesson-description-1"
              required
            ></textarea>
            <label for="lesson-file-1">Lesson 1 File:</label>
            <input
              type="file"
              id="lesson-file-1"
              name="lesson-file-1"
              required
            />
            <button class="remove-lesson-btn" data-lesson-id="1" type="button">
              Remove
            </button>
          </div>
        </div>
        <button id="add-lesson-btn" type="button">Add Lesson</button>
        <input type="hidden" value="2" id="lesson-count" name="lesson-count" />
        <input type="submit" value="Add Course" />
      </form>
    </div>
  </body>
  <script>
    const addLessonBtn = document.getElementById('add-lesson-btn');
    const lessonForm = document.getElementById('lesson-fields-container');
    let lessonCount = 2;
    const form = document.getElementById('my-form');

    form.addEventListener('submit', function (event) {
      if (lessonCount <= 1) {
        alert('Please add atleast one lesson.');
        event.preventDefault();
      }
    });

    function addNewLesson() {
      const lessonFields = `
        <div class="lesson-fields" id="lesson-${lessonCount}">
          <label for="lesson-name-${lessonCount}">Lesson ${lessonCount} Name:</label>
          <input type="text" name="lesson-name-${lessonCount}" id="lesson-name-${lessonCount}" required>

          <label for="lesson-description-${lessonCount}">Lesson ${lessonCount} Description:</label>
          <textarea name="lesson-description-${lessonCount}" id="lesson-description-${lessonCount}" required></textarea>
          
          <label for="lesson-file-${lessonCount}">Lesson ${lessonCount} File:</label>
          <input type="file" id="lesson-file-${lessonCount}" name="lesson-file-${lessonCount}" required/>

          <button class="remove-lesson-btn" data-lesson-id="${lessonCount}" type="button">Remove</button>
        </div>
      `;
      lessonForm.insertAdjacentHTML('beforeend', lessonFields);
      lessonCount++;
      document.getElementById('lesson-count').value = lessonCount;
      console.log('count  ', document.getElementById('lesson-count').value);
      // Attach click event listener to new remove lesson button
      const removeLessonBtns = document.querySelectorAll('.remove-lesson-btn');
      removeLessonBtns.forEach((btn) => {
        btn.addEventListener('click', removeLesson);
      });
    }

    function removeLesson(event) {
      const lessonId = event.target.getAttribute('data-lesson-id');
      const lessonEl = document.getElementById(`lesson-${lessonId}`);
      lessonEl.remove();

      // Update lesson count
      lessonCount--;
      document.getElementById('lesson-count').value = lessonCount;

      // Update lesson numbers/names
      const lessonEls = document.querySelectorAll('.lesson-fields');
      lessonEls.forEach((el, index) => {
        const lessonNum = index + 1;
        const lessonNameLabel = el.querySelector(
          `label[for="lesson-name-${lessonNum}"]`
        );
        const lessonNameInput = el.querySelector(
          `input[name="lesson-name-${lessonNum}"]`
        );
        const lessonDescLabel = el.querySelector(
          `label[for="lesson-description-${lessonNum}"]`
        );
        const lessonDescTextarea = el.querySelector(
          `textarea[name="lesson-description-${lessonNum}"]`
        );

        lessonNameLabel.innerText = `Lesson ${lessonNum} Name:`;
        lessonNameInput.setAttribute('name', `lesson-name-${lessonNum}`);
        lessonNameInput.setAttribute('id', `lesson-name-${lessonNum}`);
        lessonDescLabel.innerText = `Lesson ${lessonNum} Description:`;
        lessonDescTextarea.setAttribute(
          'name',
          `lesson-description-${lessonNum}`
        );
        lessonDescTextarea.setAttribute(
          'id',
          `lesson-description-${lessonNum}`
        );
      });
    }

    addLessonBtn.addEventListener('click', addNewLesson);

    // Attach click event listener to existing remove lesson buttons
    const removeLessonBtns = document.querySelectorAll('.remove-lesson-btn');
    removeLessonBtns.forEach((btn) => {
      btn.addEventListener('click', removeLesson);
    });
  </script>
</html>

course/templates/course_detail.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Course: {{ object.name }}</title>
  </head>
  <body>
    <h1>{{ object.name }}</h1>
    <p>{{ object.description }}</p>
    <h2>Lessons:</h2>
    <ul>
      {% for lesson in object.lesson_set.all %}
      <li>
        {{ lesson.name }} - {{ lesson.description }} - {{ lesson.file.url }}
      </li>
      {% endfor %}
    </ul>
  </body>
</html>

course/templates/courses.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="{% static 'base/css/courses.css' %}"
      type="text/css"
    />
    <link
      rel="shortcut icon"
      href="{%static 'base/images/web_logo.png' %}"
      type="image/x-icon"
    />
    <title>Courses</title>
  </head>
  <body>
    <div class="container">
      <div id="mySidenav" class="sidenav">
        <a href="javascript:void(0)" class="closebtn" onclick="closeNav()"
          >&times;</a
        >
        <a href="/">Home</a>
        <a href="#">About</a>
        <a href="#">Services</a>
        <a href="#">Clients</a>
        <a href="#">Contact</a>
      </div>

      {% if user.teacher %}
      <a href="{% url 'courses:add-course' %}" class="btn">Add Course</a>
      {% endif %}
      <button onclick="openNav()" class="nav_btn">&#9776;</button>
      <h2>{% if user.student %}Enrolled{% else %}Owned{% endif %} Courses</h2>
      <hr />

      <div class="card_container">
        {% if user.student %} {% if courses %} {% for enrolled in courses %}
        <div class="card">{{ enrolled }}</div>
        {% endfor %} {% else %}
        <p>No courses enrolled yet.</p>
        {% endif %} {% else %} {% if courses %} {% for course in courses %}
        <a
          style="text-decoration: none"
          href="{% url 'courses:course' pk=course.pk %}"
        >
          <div class="card">
            {{ course.name }}
            <p>{{course.description}}</p>
          </div>
        </a>
        {% endfor %} {% else %}
        <p>No courses owned yet.</p>
        {% endif %} {% endif %}
      </div>
    </div>
  </body>
  <script>
    function openNav() {
      document.getElementById('mySidenav').style.width = '250px';
    }

    function closeNav() {
      document.getElementById('mySidenav').style.width = '0';
    }
  </script>
</html>